# Generated by Django 4.1.5 on 2023-02-04 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enc_and_dec", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_path", models.CharField(max_length=255)),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="fileupload",
            name="file",
            field=models.FileField(upload_to=""),
        ),
    ]
